### PR TITLE
UI serl jsp viktor

### PR DESCRIPTION
**Pull request by pvvArienBy**
+ jsp
+css
+ images

refactor old  jsp and servlets

### CODE REVIEW

**Review by NickSuzdalev — COMMENTED** [review]
done

**Comment by Pavel-Kazlou** [comment]
appruved

**Review by Pavel-Kazlou — APPROVED** [review]
appruved

**Review by NickSuzdalev — APPROVED** [review]
Its okey

**Review by Dzmitry-Highlander — APPROVED** [review]

**Review by NickSuzdalev — COMMENTED** [review]
done

**Pull request merged**
