### PR TITLE
Feat: signIn.jsp and singhUp.jsp

### PR DESCRIPTION
**Pull request by Dzmitry-Highlander**

### CODE REVIEW

**Comment by Pavel-Kazlou** [comment]
approved

**Review by Pavel-Kazlou — APPROVED** [review]
approved

**Review by pvvArienBy — COMMENTED** [review]
is ok

**Review by pvvArienBy — COMMENTED** [review]
approwed

**Review by pvvArienBy — CHANGES_REQUESTED** [review]
aliluyya

**Pull request merged**
